git add .
git commit -m "interaction et preloader"
git push



©2026ChezFlorence—Tousdroitsréservés doit pas etre sous RainbowText et agrandis auusi P a r l o n s d e

v o t r e l a p i n . et ameliore hero il doit convertir  prend le vrai hero pour akatech.html comme animation de hero met un webp pour background initial et met des webp et webm pour la grid des 9 image et video vas y puis en mode mobile la section faq vas trop vers la droite regle ca